import { SignIn, SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const {data} = api.posts.getAll.useQuery();
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        {user.isSignedIn ? <SignOutButton/> : <SignInButton />}
        
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      <div>
        {
          data?.map((post) => (
            <div key={post.id}>
              {post.content}
            </div>
          ))
        }
      </div>
      </main>
    </>
  );
};

export default Home;
